### PR TITLE
fix: update and fix standard

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by vweevers** [comment]
This is semver-major due to reduced browser support, I'm cool with that.

Note that `messagea.js` is generated code, so perhaps we should exclude it from standard (--fix).

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
@ronag Do you foresee other breaking changes or should I go ahead and release a new major?

**Comment by ronag** [comment]
> @ronag Do you foresee other breaking changes or should I go ahead and release a new major?

I don't have any further plans at the moment.

**Comment by vweevers** [comment]
OK. Will release tomorrow; giving it some time in case someone is using this in browsers and has objections.

**Comment by vweevers** [comment]
4.0.0 (apologies for the delay).

**Pull request merged**
