### PR TITLE
Concurrent connections

### PR DESCRIPTION
**Pull request by jcrugzz**
This properly implements a test case that stalls due to a bug under high concurrency and load.

### CODE REVIEW

**Comment by juliangruber** [comment]
what do you think the reason for this is? my first guess is gc pressure. does it ever finish?

**Comment by jcrugzz** [comment]
@juliangruber it never finishes because a callback is never called for a readStream or a delete (but fairly sure its a readStream). Its something I ran into with this massive migration I'm running thats multi-process so I know its not GC pressure. I've found that tuning the concurrency in the `each-limit` when reading the data makes it more deterministic. In my live test case changing it from `Number.MAX_VALUE` to 15 allowed it to complete. The other factor here is record size. When i had it has `utf8` values, it completed without issue but when making the records bigger and changing it to `json`, it causes it to stall.

**Comment by jcrugzz** [comment]
interesting it passed!

**Comment by jcrugzz** [comment]
hmmm

**Comment by jcrugzz** [comment]
@juliangruber i originally reproduced the issue with https://github.com/jcrugzz/multileveldown-hang.

**Comment by jcrugzz** [comment]
@juliangruber so i figured out it was due mostly to the size of the `json` record stored so I think it might be a bug in https://github.com/mafintosh/pbs. The concurrency was just a contributor as well but the size of the data was a larger piece of the cause. I worked around this limitation by ensuring i didn't store any json greater than 10000 bytes.

**Comment by mafintosh** [comment]
@jcrugzz  great job! i have time to look into / fix this tomorrow

**Pull request closed without merging**
