### PR TITLE
add tests from abstract-leveldown

### PR DESCRIPTION
**Pull request by juliangruber**
some are failing, some are passing :)

consider this a WIP pull request

### CODE REVIEW

**Comment by juliangruber** [comment]
`batch-tests` are passing

**Comment by juliangruber** [comment]
ok, this is kindof pointless now, since all the tests already pass but the forced downgrade of abstract-leveldown breaks other tests. or what do you think?

**Comment by mafintosh** [comment]
why is the downgrade necessary?

**Comment by juliangruber** [comment]
because the tests that ship with current abstract-leveldown aren't compatibly with the version of levelup we're using

**Comment by juliangruber** [comment]
i'm still not sure if this test suite is even useful, i tried to break some tests by changing lines to not make sense, but they still passed

**Comment by mafintosh** [comment]
whoa haha. that doesn't sound comforting

**Pull request closed without merging**
